version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "9002:9002"
    working_dir: /app
    command: ./diep_server
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
