name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: "SO project deploy hetzner"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          ecr: false                # <— desativa ECR
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/2d-space-cells:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/2d-space-cells:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: "SO project deploy hetzner"
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/2d-space-cells:latest
            docker rm -f simulacao || true
            docker run -d \
              --name simulacao \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/2d-space-cells:latest
